global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: crypto-pipeline
    environment: production

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Crypto Pipeline Services
  - job_name: 'crypto-producer'
    static_configs:
      - targets: ['crypto-full:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  - job_name: 'crypto-consumer'
    static_configs:
      - targets: ['crypto-full:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  - job_name: 'crypto-monitor'
    static_configs:
      - targets: ['crypto-full:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Infrastructure Services
  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # PostgreSQL metrics (if pg_exporter is available)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['pg-exporter:9187']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s
  #   scrape_timeout: 10s
  #   honor_labels: true

  # Custom metrics endpoint for crypto pipeline health
  - job_name: 'crypto-health'
    static_configs:
      - targets: ['crypto-full:9091']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Rule files for alerting (optional)
# rule_files:
#   # - "first_rules.yml"
#   # - "second_rules.yml"
