global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Redpanda metrics
  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']
    metrics_path: /metrics

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Kafka metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Airflow metrics
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9092']
    metrics_path: /metrics
    scrape_interval: 30s

  # Producer metrics (if exposed)
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']
    metrics_path: /metrics

  # Consumer metrics (if exposed)
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8001']
    metrics_path: /metrics

  # Throughput monitor metrics
  - job_name: 'throughput-monitor'
    static_configs:
      - targets: ['throughput-monitor:9091']

